apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pgga

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - julia-deployment.yaml
  - pgga-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: pg-ga-conf
  app.kubernetes.io/managed-by: kustomize

images:
  - name: pgga/julia-sobol
    newTag: latest
  - name: pgga/elixir
    newTag: latest
